-- Gerado por scripts/build-seed.mjs a partir de src/app/data/meals.ts
-- Re-execute o script após alterar o array MEALS para regenerar este arquivo.

insert into public.meals (
  id, name, category, description, price, protein, carbs, calories,
  "imageUrl", rating, "isDairyFree", "isGlutenFree", "isSugarFree",
  "isArchived", "isAvailableForCombo"
) values
  ('combo-1', 'Combo Performance Semanal', 'Combo', 'Kit com 5 refeições variadas de alto teor proteico, ideal para quem busca praticidade e resultados.', 159.9, 180, 220, 2400, 'https://picsum.photos/seed/meal-combo-1/400/300', 5, false, false, true, false, true),
  ('c1', 'Peito de frango grelhado', 'Chicken', 'Peito de frango grelhado temperado.', 0, 31, 0, 165, 'https://picsum.photos/seed/c1/400/300', null, false, false, false, false, true),
  ('c2', 'Peito de frango desfiado', 'Chicken', 'Frango desfiado suculento.', 0, 28, 0, 150, 'https://picsum.photos/seed/c2/400/300', null, false, false, false, false, true),
  ('c3', 'Frango em cubos', 'Chicken', 'Cubos de frango grelhados.', 0, 30, 0, 160, 'https://picsum.photos/seed/c3/400/300', null, false, false, false, false, true),
  ('c4', 'Frango ao molho mostarda', 'Chicken', 'Frango com molho de mostarda caseiro.', 0, 29, 5, 180, 'https://picsum.photos/seed/c4/400/300', null, false, false, false, false, true),
  ('c5', 'Frango cremoso', 'Chicken', 'Frango com creme leve.', 0, 27, 8, 210, 'https://picsum.photos/seed/c5/400/300', null, false, false, false, false, true),
  ('c6', 'Frango xadrez', 'Chicken', 'Frango com pimentões e cebola.', 0, 25, 10, 190, 'https://picsum.photos/seed/c6/400/300', null, false, false, false, false, true),
  ('c7', 'Strogonoff de frango', 'Chicken', 'Clássico strogonoff com creme de leite light.', 0, 26, 12, 230, 'https://picsum.photos/seed/c7/400/300', null, false, false, false, false, true),
  ('b1', 'Patinho moído', 'Beef', 'Carne bovina magra moída.', 0, 26, 0, 220, 'https://picsum.photos/seed/b1/400/300', null, false, false, false, false, true),
  ('b2', 'Carne em tiras grelhado', 'Beef', 'Tiras de carne bovina grelhadas.', 0, 28, 0, 240, 'https://picsum.photos/seed/b2/400/300', null, false, false, false, false, true),
  ('b3', 'Carne moída cozida com legumes', 'Beef', 'Mix nutritivo de carne e legumes.', 0, 24, 8, 210, 'https://picsum.photos/seed/b3/400/300', null, false, false, false, false, true),
  ('b4', 'Carne de panela', 'Beef', 'Carne bovina cozida lentamente.', 0, 25, 5, 250, 'https://picsum.photos/seed/b4/400/300', null, false, false, false, false, true),
  ('b5', 'Carne desfiada', 'Beef', 'Carne bovina desfiada e temperada.', 0, 27, 0, 230, 'https://picsum.photos/seed/b5/400/300', null, false, false, false, false, true),
  ('b6', 'Almôndegas', 'Beef', 'Almôndegas bovinas artesanais.', 0, 22, 10, 260, 'https://picsum.photos/seed/b6/400/300', null, false, false, false, false, true),
  ('b7', 'Carne moída ao molho de tomate', 'Beef', 'Carne moída com molho natural.', 0, 23, 6, 220, 'https://picsum.photos/seed/b7/400/300', null, false, false, false, false, true),
  ('b8', 'Fígado', 'Beef', 'Fígado bovino grelhado.', 0, 24, 4, 175, 'https://picsum.photos/seed/b8/400/300', null, false, false, false, false, true),
  ('o1', 'Filé de tilápia', 'Fish', 'Peixe branco grelhado ou cozido.', 0, 20, 0, 130, 'https://picsum.photos/seed/o1/400/300', null, false, false, false, false, true),
  ('o2', 'Camarão', 'Fish', 'Camarões frescos grelhados.', 0, 18, 1, 100, 'https://picsum.photos/seed/o2/400/300', null, false, false, false, false, true),
  ('cb1', 'Arroz branco', 'Carbs', 'Arroz branco soltinho.', 0, 3, 28, 130, 'https://picsum.photos/seed/cb1/400/300', null, false, false, false, false, true),
  ('cb2', 'Arroz integral', 'Carbs', 'Arroz integral nutritivo.', 0, 3, 25, 120, 'https://picsum.photos/seed/cb2/400/300', null, false, false, false, false, true),
  ('cb3', 'Arroz parboilizado', 'Carbs', 'Arroz parboilizado de qualidade.', 0, 3, 27, 125, 'https://picsum.photos/seed/cb3/400/300', null, false, false, false, false, true),
  ('cb4', 'Arroz 7 grãos', 'Carbs', 'Mix especial de grãos integrais.', 0, 5, 24, 140, 'https://picsum.photos/seed/cb4/400/300', null, false, false, false, false, true),
  ('cb5', 'Feijão carioca', 'Carbs', 'Clássico feijão carioca.', 0, 5, 14, 80, 'https://picsum.photos/seed/cb5/400/300', null, false, false, false, false, true),
  ('cb6', 'Feijão preto', 'Carbs', 'Feijão preto temperado.', 0, 6, 15, 85, 'https://picsum.photos/seed/cb6/400/300', null, false, false, false, false, true),
  ('cb7', 'Feijão fradinho', 'Carbs', 'Feijão fradinho cozido.', 0, 7, 18, 110, 'https://picsum.photos/seed/cb7/400/300', null, false, false, false, false, true),
  ('cb8', 'Feijão branco', 'Carbs', 'Feijão branco suculento.', 0, 6, 16, 95, 'https://picsum.photos/seed/cb8/400/300', null, false, false, false, false, true),
  ('cb9', 'Feijão de corda (feijão verde)', 'Carbs', 'Tradição regional.', 0, 6, 14, 85, 'https://picsum.photos/seed/cb9/400/300', null, false, false, false, false, true),
  ('cb10', 'Grão-de-bico', 'Carbs', 'Grão-de-bico cozido.', 0, 8, 20, 160, 'https://picsum.photos/seed/cb10/400/300', null, false, false, false, false, true),
  ('cb11', 'Macarrão integral', 'Carbs', 'Pasta de trigo integral.', 0, 6, 26, 150, 'https://picsum.photos/seed/cb11/400/300', null, false, false, false, false, true),
  ('cb12', 'Macarrão de arroz', 'Carbs', 'Opção sem glúten.', 0, 3, 25, 120, 'https://picsum.photos/seed/cb12/400/300', null, false, false, false, false, true),
  ('cb13', 'Macarrão de abobrinha', 'Carbs', 'Baixo carboidrato.', 0, 1, 3, 20, 'https://picsum.photos/seed/cb13/400/300', null, false, false, false, false, true),
  ('cb14', 'Macarrão normal (penne, espaguete)', 'Carbs', 'Massa clássica.', 0, 5, 30, 160, 'https://picsum.photos/seed/cb14/400/300', null, false, false, false, false, true),
  ('cb15', 'Batata inglesa (refogada, rústica)', 'Carbs', 'Batata inglesa preparada com ervas.', 0, 2, 17, 80, 'https://picsum.photos/seed/cb15/400/300', null, false, false, false, false, true),
  ('cb16', 'Batata-doce (cozida, grelhada)', 'Carbs', 'Batata-doce energética.', 0, 2, 20, 90, 'https://picsum.photos/seed/cb16/400/300', null, false, false, false, false, true),
  ('cb17', 'Macaxeira (cozida, grelhada)', 'Carbs', 'Mandioca cozida ou grelhada.', 0, 1, 38, 160, 'https://picsum.photos/seed/cb17/400/300', null, false, false, false, false, true),
  ('cb18', 'Abóbora (leite, jacarezinho)', 'Carbs', 'Abóbora cozida.', 0, 1, 7, 30, 'https://picsum.photos/seed/cb18/400/300', null, false, false, false, false, true),
  ('cb19', 'Purê de batata doce', 'Carbs', 'Cremoso de batata doce.', 0, 2, 18, 100, 'https://picsum.photos/seed/cb19/400/300', null, false, false, false, false, true),
  ('cb20', 'Purê de batata inglesa', 'Carbs', 'Cremoso de batata inglesa.', 0, 2, 15, 90, 'https://picsum.photos/seed/cb20/400/300', null, false, false, false, false, true),
  ('cb21', 'Purê de jerimum', 'Carbs', 'Purê de abóbora.', 0, 1, 6, 40, 'https://picsum.photos/seed/cb21/400/300', null, false, false, false, false, true),
  ('v1', 'Brócolis', 'Veggie', 'Brócolis frescos no vapor.', 0, 3, 7, 35, 'https://picsum.photos/seed/v1/400/300', null, false, false, false, false, true),
  ('v2', 'Couve-flor', 'Veggie', 'Couve-flor no vapor.', 0, 2, 5, 25, 'https://picsum.photos/seed/v2/400/300', null, false, false, false, false, true),
  ('v3', 'Cenoura', 'Veggie', 'Cenouras cozidas ou rústicas.', 0, 1, 10, 40, 'https://picsum.photos/seed/v3/400/300', null, false, false, false, false, true),
  ('v4', 'Abobrinha', 'Veggie', 'Abobrinha grelhada.', 0, 1, 3, 20, 'https://picsum.photos/seed/v4/400/300', null, false, false, false, false, true),
  ('v5', 'Chuchu', 'Veggie', 'Chuchu cozido.', 0, 1, 4, 20, 'https://picsum.photos/seed/v5/400/300', null, false, false, false, false, true),
  ('v6', 'Vagem', 'Veggie', 'Vagem salteada.', 0, 2, 7, 30, 'https://picsum.photos/seed/v6/400/300', null, false, false, false, false, true),
  ('v7', 'Abóbora (leite, jacarezinho)', 'Veggie', 'Abóbora cozida.', 0, 1, 7, 30, 'https://picsum.photos/seed/v7/400/300', null, false, false, false, false, true),
  ('v8', 'Beterraba', 'Veggie', 'Beterraba cozida.', 0, 2, 10, 45, 'https://picsum.photos/seed/v8/400/300', null, false, false, false, false, true),
  ('v9', 'Couve folha (refogada)', 'Veggie', 'Couve refogada com alho.', 0, 2, 6, 30, 'https://picsum.photos/seed/v9/400/300', null, false, false, false, false, true),
  ('v10', 'Quiabo (refogado)', 'Veggie', 'Quiabo refogado.', 0, 2, 7, 35, 'https://picsum.photos/seed/v10/400/300', null, false, false, false, false, true),
  ('v11', 'Ervilha', 'Veggie', 'Ervilhas frescas.', 0, 5, 14, 80, 'https://picsum.photos/seed/v11/400/300', null, false, false, false, false, true),
  ('v12', 'Milho verde', 'Veggie', 'Milho verde cozido.', 0, 3, 19, 85, 'https://picsum.photos/seed/v12/400/300', null, false, false, false, false, true),
  ('v13', 'Seleta de legumes', 'Veggie', 'Mix de cenoura, batata, abobrinha, milho, ervilha.', 0, 2, 12, 60, 'https://picsum.photos/seed/v13/400/300', null, false, false, false, false, true),
  ('v14', 'Mix Brócolis, Cenoura e Couve-flor', 'Veggie', 'Mix clássico de vegetais.', 0, 2, 8, 45, 'https://picsum.photos/seed/v14/400/300', null, false, false, false, false, true)
on conflict (id) do nothing;
